### ISSUE TITLE
R Session aborts

### ISSUE THREAD

**Issue by Wurzelqueen** [seananderson/covidseir#10]
Tried to run the `covidseir` package and the R session always aborts, even if i try the relatively simple example from the vignette: https://seananderson.github.io/covidseir/articles/fitting-case-data.html
When it comes to plotting the result with this line (tried different plotting possibilities, also leads to abortion): 
```
covidseir::plot_projection(tidy_proj, obs_dat = dat,
                           value_column = "value", date_column = "date") 
```
The seesion aborts, also if i try to run the package with different data.

**Comment by seananderson** [comment]
Does a basic example work for you with rstan itself? This sounds like a C++ compiler issue or something more general.

```r 
library(rstan)
scode <- "
parameters {
  real y[2]; 
} 
model {
  y[1] ~ normal(0, 1);
  y[2] ~ double_exponential(0, 2);
} 
"
fit1 <- stan(model_code = scode, iter = 10, verbose = FALSE) 
print(fit1)
```

**Comment by Wurzelqueen** [comment]
Yes, rstan itself (also your example) works! I figured out, that if i don't run this line: `future::plan(future::multisession)` It works perfectly fine and the R session doesn't abort anymore. Thanks a lot anyway for your answer :)
