### ISSUE TITLE
Error when using "NUTS" estimation

### ISSUE THREAD

**Issue by Wurzelqueen** [seananderson/covidseir#14]
I used the following values for fit_seir:

```
fit <- covidseir::fit_seir(
  daily_cases = dat$new_cases, 
  #obs_model = c("NB2", "Poisson"),
  #forecast_days = 0,
  time_increment = 0.25,
  samp_frac_fixed = samp_frac,
  samp_frac_type = c("fixed"),
  f_seg = f_seg, 
  #days_back = 45, 
  R0_prior = c(log(2.6), 0.2),
  #phi_prior = 1,
  f_prior = c(0.4, 0.2), 
  i0_prior = c(log(3.61), 1), 
  e_prior = c(0.85, 0.05), 
  start_decline_prior = c(log(47), 0.1),
  end_decline_prior = c(log(59), 0.1), SD
  chains = 5,
  iter = 2000, 
  pars = c(D=7, k1 = 0.196, k2 = 3, q = 1/5, ud = 0.1, ur = 0.02, f0 = 1),
  N_pop = 4761865,
  fit_type = "NUTS" 
)
```
If i use the estimation method MAP so, "optimizing" it works fine, no error occurs. For a final estimation i wanted to use MCMC, so "NUTS" and get the following error for several chains: 

```
SAMPLING FOR MODEL 'seir' NOW (CHAIN 3).
Chain 3: Rejecting initial value:
Chain 3:   Error evaluating the log probability at the initial value.
Chain 3: Exception: neg_binomial_2_log_lpmf: Log location parameter[240] is nan, but must be finite!  (in 'model_seir' at line 319)
```

Can't find the mistake though i used (mostly) same parameters as shown in the vignette.

**Comment by seananderson** [comment]
Can you include `dat$new_cases` and `samp_frac` so I can reproduce this? You could use `dput(dat$new_cases)` and `dput(samp_frac)` and paste here.

**Comment by Wurzelqueen** [comment]
Figured out that if i change the parameter q to 0.05 instead of 1/5 it works fine and the error doesn't occur anymore. Can't explain why but works now, thanks  a lot anymways!
